language: python
python:
    - "2.7"
services:
    - postgresql
before_script:
    - cp sasmarket/settings.py.example sasmarket/settings.py
install: "pip install -r requirements.txt"
script: python manage.py test marketplace
