language: python
python:
  - '2.7'
services:
  - postgresql
before_script:
    - cp sasmarket/settings.py.example sasmarket/settings.py
    - dropdb marketplace --if-exists
    - createdb marketplace
    - python manage.py migrate
install: pip install -r requirements.txt
script: python manage.py test marketplace
before_install:
    - openssl aes-256-cbc -K $encrypted_1645300b04d0_key -iv $encrypted_1645300b04d0_iv -in deploy_key.pem.enc -out deploy_key.pem -d
deploy:
    provider: script
    script: deploy.sh
    on:
        branch: master
