language: python
python:
- '2.7'
services:
- postgresql
before_install:
- openssl aes-256-cbc -K $encrypted_1645300b04d0_key -iv $encrypted_1645300b04d0_iv
  -in .travis/travis_rsa.enc -out .travis/travis_rsa -d
before_script:
- echo -e "Host danse.chem.utk.edu\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- cp sasmarket/settings.py.example sasmarket/settings.py
- createuser sasmodeluser
- dropdb test_marketplace --if-exists
- dropdb marketplace --if-exists
- dropdb test_sasmodeldatabase
- dropdb sasmodeldatabase
- createdb test_marketplace
- createdb marketplace
- createdb test_sasmodeldatabase
- createdb sasmodeldatabase
- python manage.py migrate
install: pip install -r requirements.txt
script: python manage.py test marketplace
deploy:
  skip_cleanup: true
  provider: script
  script: /bin/sh -xe ./deploy.sh
  on:
    branch: master
notifications:
  slack:
    secure: GIg+/pvs3C+zmMCzkCTcQSC3poQktW517dh4BpCIXSAIjjw2glaJSqnF+yD0X/rTOT/Cq9bn7vYQxqSxMC/iXTaGExAjRHqqtQkCJ4kAwB/BQyCRVGUPMYZuYty+TihoffdpvbGEDhtG7u+OPVGpqlHwsCPtSntDiPFCpBqt1uKgkdLNYeUbItEvcdp7nHAriBY0CrlllTeGpHXEDQEIzUi+5hiZ14xPjLBLpfDdyzCY/O3tzGzxxlUTaCwa4A51Xom6ratHx11WTEKNHDTcdDESfvJN+uoVKUy1j30mywD/0d6nSraRokj4VdpXi2l1NQlHVArPtnq6lvTis7t8eEzSYBoKyYMPFy5l3xTuKWbX5UkQU/fEV7FZNfOPak0r4RPTxppdj9li/reZDUyLeftaITxJfx3uXibumsCe9KWMI6NYWChLv8QCllyp6nBZbm4eavdoMf2plNamz5pP4GOwwe3pIApHEh1QD8QZ1HW8C+JeiWzpNwT998sQgeprsf9n9D/qCcnpyo/6lSEqnqX8PkAmS7VuIWjwcmX839TlL0uoxA9jU5VP5BOU8IYRv9qxNuN6MdjJdnn2vo3pNofX9hZineXn4azucbqwHdGZqn8lm8lMzmhWorsS6zv5P8d1wYZ80my1KUhG+gNUem1qL8Xssp2AemkOGLASjlc=
