language: python
python:
    - "2.7"
    - "3.2"
    - "3.4"
services:
    - postgresql
before_script:
    - cp sasmarket/settings.py.example sasmarket/settings.py
    - dropdb marketplace --if-exists
    - createdb marketplace
    - python manage.py migrate
install: "pip install -r requirements.txt"
script: python manage.py test marketplace
