language: python
python:
    - '2.7'
services:
    - postgresql
before_install:
    - openssl aes-256-cbc -K $encrypted_1645300b04d0_key -iv $encrypted_1645300b04d0_iv -in .travis/travis_rsa.enc -out .travis/travis_rsa -d
before_script:
    - echo -e "Host danse.chem.utk.edu\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - cp sasmarket/settings.py.example sasmarket/settings.py
    - dropdb marketplace --if-exists
    - createdb marketplace
    - python manage.py migrate
install: pip install -r requirements.txt
script: python manage.py test marketplace
# after_success:
#     - eval "$(ssh-agent -s)" #start the ssh agent
#     - chmod 600 .travis/travis_rsa
#     - ssh-add .travis/travis_rsa
#     - git remote add deploy git@danse.chem.utk.edu:/var/www/marketplace.sasview.org
#     - git push deploy
deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: master
