# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_sasviewmodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sasviewmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
