# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import marketplace.backends.database


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_delete_uploaded_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='sasviewmodel',
            name='model_file',
            field=models.FileField(default='', storage=marketplace.backends.database.DatabaseStorage(), upload_to=b'uploaded_models'),
            preserve_default=False,
        ),
    ]
