# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 09:55
from django.db import migrations, models
import django.db.models.deletion
import marketplace.backends.database


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_sasviewmodel_file_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_file', models.FileField(storage=marketplace.backends.database.DatabaseStorage(), upload_to=b'uploaded_models')),
            ],
        ),
        migrations.RemoveField(
            model_name='sasviewmodel',
            name='model_file',
        ),
        migrations.AddField(
            model_name='modelfile',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.SasviewModel'),
        ),
    ]
