# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_auto_20160902_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False, unique=True),
        ),
    ]
