# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-07 09:07
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sasviewmodel',
            name='example_data_x',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator(re.compile(b'^([-+]?\\d*\\.?\\d+[,\\s]*)+$'), 'Must be a list of comma separated float values', b'invalid')]),
        ),
        migrations.AlterField(
            model_name='sasviewmodel',
            name='example_data_y',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator(re.compile(b'^([-+]?\\d*\\.?\\d+[,\\s]*)+$'), 'Must be a list of comma separated float values', b'invalid')]),
        ),
        migrations.AlterField(
            model_name='sasviewmodel',
            name='verfied_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sasviewmodel',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models_verified', to=settings.AUTH_USER_MODEL),
        ),
    ]
