# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-07 09:32
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_auto_20170407_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sasviewmodel',
            name='example_data_x',
            field=models.CharField(blank=True, max_length=5000, null=True, validators=[django.core.validators.RegexValidator(re.compile(b'^([-+]?\\d*\\.?\\d+[,\\s]*)+$'), 'Must be a list of comma separated float values', b'invalid')]),
        ),
        migrations.AlterField(
            model_name='sasviewmodel',
            name='example_data_y',
            field=models.CharField(blank=True, max_length=5000, null=True, validators=[django.core.validators.RegexValidator(re.compile(b'^([-+]?\\d*\\.?\\d+[,\\s]*)+$'), 'Must be a list of comma separated float values', b'invalid')]),
        ),
    ]
