# Generated by Django 3.1.5 on 2021-06-01 17:25

import django.core.validators
from django.db import migrations, models
import marketplace.backends.database
import re


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_auto_20170407_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfile',
            name='model_file',
            field=models.FileField(storage=marketplace.backends.database.DatabaseStorage(), upload_to='uploaded_models'),
        ),
        migrations.AlterField(
            model_name='sasviewmodel',
            name='example_data_x',
            field=models.CharField(blank=True, max_length=5000, null=True, validators=[django.core.validators.RegexValidator(re.compile('^([-+]?\\d*\\.?\\d+[,\\s]*)+$'), 'Must be a list of comma separated float values', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='sasviewmodel',
            name='example_data_y',
            field=models.CharField(blank=True, max_length=5000, null=True, validators=[django.core.validators.RegexValidator(re.compile('^([-+]?\\d*\\.?\\d+[,\\s]*)+$'), 'Must be a list of comma separated float values', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='sasviewmodel',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='sasviewmodel',
            name='verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
