# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-07 09:32
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_auto_20170407_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='sasviewmodel',
            name='model_version',
            field=models.PositiveSmallIntegerField(default=1, null=False, blank=False),
        ),
        migrations.AddField(
            model_name='sasviewmodel',
            name='sasview_version',
            field=models.CharField(max_length='6', default=None, null=True, blank=True),
        ),
    ]
