name: Build and Depoly
on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
    - name: Set Up PostgresSQL
      run: |
        sudo apt-get install posregresql libpq-dev
        sudo service postgresql start
    - uses: actions/checkout@v2
    - run: |
        mkdir ~/.ssh
        echo -e "Host danse.chem.utk.edu\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        cp sasmarket/settings.py.example sasmarket/settings.py
        createdb marketplace
        python manage.py migrate
#  deploy:
#    name: deploy
#    needs: build
#    runs-on: ubuntu-20.04
