name: Build and Depoly
on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: |
        sudo apt-get -y install postgresql
        echo "postgres:postgres" | sudo chpasswd
        sudo su - postgres -c "./sasmodel-marketplace/scripts/postgres_setup.sh"
        mkdir ~/.ssh
        echo -e "Host danse.chem.utk.edu\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        cp sasmarket/settings.py.example sasmarket/settings.py
        createdb marketplace
        python manage.py migrate
#  deploy:
#    name: deploy
#    needs: build
#    runs-on: ubuntu-20.04
