name: Build and Deploy
on: [push, pull_request]

jobs:
  vm-job:
    name: build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # Keep general for future DB transitions
        db: [ mysql ]
        # Keep general for future python version compatibility
        python-version: [ 3.8 ]
        include:
          - db: mysql
            db_name: marketplace
            db_user: mysql
            db_password: test
            root_password: root
            host: 172.18.0.1
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ matrix.root_password }}
          MYSQL_DATABASE: ${{ matrix.db_name }}
          MYSQL_USER: ${{ matrix.db_user }}
          MYSQL_PASSWORD: ${{ matrix.db_password }}
          MYSQL_HOST: ${{ matrix.host }}
          DB_PARAMS: ${{ job.services.mysql }}
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: install prerequisites
        run: sudo apt-get install -y python3-dev python3-setuptools libpq-dev apache2-dev mysql-client
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start mysql service
        run: sudo /etc/init.d/mysql start
      - name: Create django db and user; grant full access
        run: sudo bash scripts/mysql_setup.sh
      - name: Migration and Tests
        env:
          # These DBs and passwords are *not* production passwords.
          # They are throwaways for testing transient github instances
          DB: ${{ matrix.db_name }}
          DB_HOST: ${{ matrix.host }}
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
          DB_USER: ${{ matrix.db_user }}
          DB_PASSWORD: ${{ matrix.db_password }}
        run: |
          cp sasmarket/settings.py.example sasmarket/settings.py
          python manage.py migrate
          python manage.py test
#  deploy:
#    name: deploy
#    needs: build
#    runs-on: ubuntu-20.04
