name: Build and Deploy
on: [push, pull_request]

jobs:
  vm-job:
    name: build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # Keep general for future DB transitions
        db: [ mysql ]
        # Keep general for future python version compatibility
        python-version: [ 3.8 ]
        include:
          - db: mysql
            host: 172.18.0.1
    env:
      MYSQL_DATABASE: marketplace
      MYSQL_USER: mysql
      MYSQL_PASSWORD: test
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    steps:
      # MySQL is installed natively on Ubuntu 20.04 - no need to add as a service, simply start it
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE USER '${{ env.MYSQL_USER }}'@'localhost' IDENTIFIED BY '${{ env.MYSQL_PASSWORD }}';"
          mysql -e "GRANT ALL PRIVILEGES ON ${{ env.MYSQL_DATABASE }}.* TO '${{ env.MYSQL_USER }}'@'localhost';"
      - uses: actions/checkout@v2
      - name: install prerequisites
        run: sudo apt-get install -y python3-dev python3-setuptools libpq-dev apache2-dev mysql-client
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Migration and Tests
        run: |
          cp sasmarket/settings.py.example sasmarket/settings.py
          python manage.py migrate
          python manage.py test
#  deploy:
#    name: deploy
#    needs: build
#    runs-on: ubuntu-20.04
