name: Build and Deploy
on: [push, pull_request]

jobs:
  vm-job:
    name: build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # Keep general for future DB transitions
        db: [ mysql ]
        # Keep general for future python version compatibility
        python-version: [ 3.8 ]
        include:
          - db: mysql
            db_user: root
            db_password: root
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mysql
        ports:
          - '3306:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Migration and Tests
        env:
          # These DBs and passwords are *not* production passwords.
          # They are throwaways for testing transient github instances
          DB: ${{ matrix.db }}
          DB_HOST: 127.0.0.1
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
          DB_USER: ${{ matrix.db_user }}
          DB_PASSWORD: ${{ matrix.db_password }}
        run: |
          cp sasmarket/settings.py.example sasmarket/settings.py
          python manage.py migrate
          python manage.py test
#  deploy:
#    name: deploy
#    needs: build
#    runs-on: ubuntu-20.04
